-- Depoimentos: avaliações reais do Google (sincronizado em 2026-09-02) -----
delete from public.testimonials;

insert into public.testimonials (name, city, stars, text, photo, photos, sort) values
('Elaine Carmo','Avaliação no Google',5,'A minha experiência foi a melhor possível, viagem super agradável, claro contratempos acontecem mas foi tudo conduzido da melhor maneira possível, nosso guia super atencioso. O que foi oferecido foi cumprido, hospedagem foi maravilhosa, café da manhã todos os dias maravilhoso e o atendimento também. Para minha primeira viagem eu amei. E super indico a Renantur Viagens.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNetdAW1IdSXckiY0G0XLdw9uVkKEsWtzXBlD1SBgNMNae-CGjyK73h2wY3M1NMv5zGo_ufgiZPAF7O35Ugvkb6YUihG-9uKW5RhnhDEP2j6HggFT1--5vUwaorKY-4aGFMj02IGhWtdDGj=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOyOzCY8k8hFp1JvRhHfU4etDOgJ0miOErgOgcQFyo_ql2qsMTk-L370YGvGimwvtnMKv2QbeuT0e2huTqOwZ-AMHVE4u9HSA0Wrt1-z1WYqKrbSHWAh5P6GEN7j3_akK_Sd8g9LFTkrgo=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmPEj_uIvfvaOuEtn4Xbl47bNdqm3z4PQMYJO1mO-_dL4qgZxTiT_A_QsO8_O0gzACr5FFSn9o5p4e3AW4NzHY_LlvJM9BVGUfhIFjoxYKh487x0U5rTKDAK4wSa9VvRJ19YL64h9C4l6lU=w300-h225-p-k-no'],1),
('Jeniffer Sayuri','Avaliação no Google',5,'Experiência nota 1000! Quero agradecer à Renantur por organizar tudo com tanto cuidado. Desde o primeiro contato até a volta para casa, foi tudo impecável. E um agradecimento especial ao guia Renan. Atencioso, paciente e com um conhecimento incrível sobre cada lugar. Fez toda diferença na nossa viagem! Recomendo de olhos fechados. Já estou planejando a próxima com vocês!','','{}',2),
('Mariane Braz','Avaliação no Google',5,'Super recomendo a Renantur Viagens pelo atendimento, responsabilidade, organização e atenção com cada um. Viagem para Foz do Iguaçu x Paraguai x Argentina foi extremamente espetacular... roteiro top.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmOyu8pxUbykPaQk7YkprfaJbs01SgVv_r_Yi2Lf4Z0Ddtog2S4snxhAWNyQgl_ni1KJEZOJZa611u5ggTHwtWuBHaeD9tTzPdsVFcyMxDU2mUsr1ea67iykaMH5p5Eo9d79O9lKM6MRMfQ=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmPJObs3RRc-xC81BuF-3lHDHzoqwUCTox4194L9WU3ufg_SHpvDdyWYWzBYjs8Cjlo6rgzal0nUGsuaHI5TqsFQ3Jd186P8XGM-lJaE2EwwBJEemFJUAuToRyUu6POnCMBd-YTCwaymr43J=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOLWZwWYK2yYDNNCLYw8g4_8spPxK-t2GSpk4ytc4UO9Ev_HxHdoBkQ3es5BqFhHbeE3mCZVtiGiZ1E9c7qTO5jHy3kscXikPf6ne4TykJNqdOi9T1I22fB189X_8jgBJwwd3bC9xytB4xH=w300-h225-p-k-no'],3),
('Maria Lucia Soares','Avaliação no Google',5,'A viagem foi tranquila, Renan e os guias locais muito atenciosos. Todos os passeios inclusos na programação do pacote de viagem para Foz do Iguaçu foram realizados.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmPWy-i1N1-XgbyPn6fUsHc6r4Oh9GFy34Y9aUKFhT6nxITFwh8XkO43vP-wb6mPuJY280Tzgeq0nm3-7SKiLihEZDOLVr0f2JBpEYlNKdcgX78WI0an8VUNbVytHvkPZvKb2JAvDoUTfrRM=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOvqkGZUXXJPrx9lpd8PwhQsFEOcDN0tW2S9A1rriK_WKpwndy_Z-kZubyL5kRA9LtyICq4LhuUc8qQ6GAi3WqDV8tA3VHl_bFfQLF4vA_UmlLgmIa0JcDiW0zJAKZs4hPr6SHO3nYUklU=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOFrZP2stas0hFm7yOXVGUeExGRkVX5zaHG9qn7X2MYWxIo0u5MJHMIuhhrgtfF361wh96EcdL9nleuA_BB9LEZR4ijOkoCd54EqxpkDsDCgnoLATjSjLijyBN2Y-MhJ6uH7chkR5coRxQ=w300-h225-p-k-no'],4),
('Valéria Andrade','Avaliação no Google',5,'Viagem para Sampa Sky sensacional, com visita ao Mercado Municipal e Bairro da Liberdade. Passeio com conforto e segurança, parabéns toda equipe Renantur Viagens.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmO5KIYSTHR56uEao_s7oUsOn4v6PMHonU-4TFrh23KuS6HBRW49hwCWkEasS3ZTOhJpZpbG7r6RWhJwS6BBeQ5qasSNVKZ_cJuAzmjjSoVxLqQFkaUmzg9wyd_iphfVhHRRz1gZIDwhPzSs=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmPnKxVYWw_kZk9QasaELyXwAim8AUwlkASM5SK1DMNJs5jGD4-vClsHCst8kdl7EiNls_0ktH0FP0U7Esud99TGazvlLYLDTLvUpZWPdL70EvC8LhDLc4YUBqKtPpeDy0ApVv0W5pQnU_0A=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmNhTVMZ5T0eo1ncAsUwYfmdQl-yrhws4VGvxMll8kHAAWJAkdZImW8expXeG-ZIZhXpq9cD-RPrq_R2COCaN8S8CpF6mSymOESSNOddMcvH6S98DNDSY26CtKMIuK5r0pT37uJ3f57u1_un=w300-h225-p-k-no'],5),
('Maria da Glória Silva','Avaliação no Google',5,'Amei ir no Sampa Sky e no mercadão, já na praça da Liberdade achei muito cheio, mas matei minha curiosidade sobre esse bairro... viagem tranquila com atendimento nota 10, principalmente por parte da organização representada pelo Renan, sempre junto, muito atencioso e paciente.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmP7mC61cDLFl1KnjpeP1-GbAN6b_LZ0TU4ZZMZQTtmk6Z-pVEb9C49VK8-n5eLHfHKZK4drwJt_rjUb3D6fbI1TiT9vqj5difJJAWjISqT1tDp7AG7QOTn6MFesPbOzHw-teBwyLNRx79at=w300-h450-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmM9GMDVYIKn25KPthQpfY_8WH7i17CKxP-MmI39i7WUPNYvfg86-DKOwGwSnAmZX6kBV65x4w07p7ZoLCLnuYad2D8UndxmXo7IMWyjm30dg6rj-GFmGe-dRi0buVnUMWt88te7gayU1FU=w300-h450-p-k-no'],6),
('Fatima Aires','Avaliação no Google',5,'Minha primeira viagem com a Renantur, está sendo uma experiência maravilhosa, tudo perfeito... farei outras viagens, se Deus quiser!!','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNOHz0w5vToVfK0q8EZja1ZRMQWfgiwdbKBTAuvnEcicusZX4wwFJ7lGUVifj5V0LFu0hSHqR5l_GPGGtjeTwVnn6x4VJ2bLd9OKJRB4Jk1oAes6XlmsZbBOCCf_qabvCgBIKwMGIFp8Zq2=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOU_Zi9A8KSRcu89QCKE1MswIgPywlqnc4-irE_7ca3FgqhoEEBUOsqA1NrRiaR2FtYBeOCW2MIsH7vtO-9cSG_yMY2DOdsOFKhL21t0Vbpg5Cz9tDoR7xu4Ow3Je5f1DI9lxscg0uNN-zc=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmMb6TJsvXsxLm2ahJzwIbIjWIAiA8gC8oJQwRBXO9wmo9Rbubx0o8kVE8LFp1BP0yjbGZQWpcS5vtqxdMnC6NQ6TY2G1XzytCIai2IoYMBRICYBvkRxRE3V0KJNtRgyZfBvviH99G3I8t3S=w300-h225-p-k-no'],7),
('mundo da maria','Avaliação no Google',5,'Passeio muito bom! Renan muito educado e atencioso! Vou viajar com ele outras vezes... com certeza. Super recomendo!','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmMEUqmVYvqh5gDxKika0udwCapAdYAM68y89tXZMI6mAxA59Phiov5-VGklKfjyrNPrcY6U4JbQGWTFwIPeXt-7ODW1dcZpLCkF2VJ09lp1UlCIfBwR4DHl1jxZZjdd5nPSjR-QgSZFlHci=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmP8KwaNP0WL9z1y5E3syzTUeiyoK8B8clAtgd_GnGLW3-I3aGGd0PuvkZKiMVsqJoJwM4sIMnu5--zv4FevXSFX0mZ7qorXgplP29WYVbbOnps2nobAKX8sEa3sKzQp13v1W8ylFx0M-TMx=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmP62QYgkHdmfndIFzTolE8Hds3oWa-GS62Y2BkEBj36UrlrfOhqgbtziS7mZ1WhKCFewBf6QlB3MjuehcdQxPtQYpLDV-_sp5FUV60y2AvJMAFX7JF5g3Ysou6k9JHFhTHg0qQdSyhdAEIh=w300-h225-p-k-no'],8),
('Ana Lucia','Avaliação no Google',5,'Ótimo passeio, super recomendo. Foi maravilhoso, amo viajar com Renan.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNtHAWmYWQmCJKy9GKhH4XuCFcC2QhNLWAgYZCX3iA3o7b9AMvJb_R5ms5wBfmRSBJ8J_6oD1h4fnJGvAiMiTGpCO0ECa1QWQku3KWQ2WxlrLTh_lwfDEnkWdwuYPf5gbI4p7y2rIktyYgU=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOSm0C8p5vaW1Qepg7lkayoSzR_Eem6v04cIuutyZ8yUEfAvcvjFmChYpZT8vLQKWoxGD-fP9pbQENrcePwXyURBa45ZFNhCuXy8tqa-2hDSDAF37U-OmoRV6HHXzA0yAoK3hyzZFutEDqh=w300-h225-p-k-no'],9),
('Maristela Landim','Avaliação no Google',5,'A viagem foi super agradável, com horários bem definidos e organizados, atenciosos. Super recomendo! Amamos!','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNcE6AaZNBhGw2XOyWQbvDwCkb2JqFiJz1nA_MSy2FU7QtJ0SgetT47TYEGmuhwL2fa0ED0oKKdxnf_lsfob0XlZU1VgzZFaW6WQg0DnAqCwi5wbw29xitmKcOfJC2AGIWcTm9QHcYtYt4=w600-h450-p-k-no'],10),
('Juliana De Carvalho','Avaliação no Google',5,'Eu amei o passeio, o transporte bom, o guia muito simpático e atencioso, deixa a gente bem à vontade, nota 10000000, vou de novo se Deus quiser.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNsR8B_CfXdgMtmk43bk0PadQe_jmzrdjyzMABSpnnvFKzzR64GngtdOBhLnyTZHcCsyaCyJewZ5BzA07zZx6IiVx6FrP1M0J9fkG7H__zsIxglJ1DftMxL_LrC9E9L8zPvccGx3cKKrbk=w300-h450-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmMIfYjOr4eTH94Ccgff2ViQNSvt7k03GwRHrcKr17tN7F1wUT6nZvQkAU_uqO6_K04Ezh5s4uE9EZje9aYHoj24JsYDprgOciXMGvWHpCZJYeDGRylj1WN5U-b2oKucaJLXVQPBmXMLa_QH=w300-h225-p-k-no'],11),
('Fernando José De Rezende','Avaliação no Google',5,'Ótima viagem, excelente atendimento o tempo todo, ótimo hotel e um guia maravilhoso. Quero voltar mais vezes.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNcD4VjJjlNW3B4yo1oBEtBG29YdbGw2a7rkzmnSdAadCrq1JoAkxxHrGqQwv8_vNE27AZIoxNCYqpukPbQe5M-cpRf_iQDB2bSV04jzCsvWWkJ7npDvIkwfJVBUIGOJb37YIVADpeiJn6f=w300-h450-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmPYycAOIVDMOaeQHrLnzT3JKfWdKqZWeXQry2ElGf4bv0pmUFLGEftVxvFt286SNH6a6W12HWxfdw8Q0vxD38byxHpnKO2v4-Ul7a5Off-xmzIwIc7NL6RmZiiIgdoemGoX2--R0nTLK4mK=w300-h225-p-k-no'],12),
('Katia Araújo','Avaliação no Google',4,'Minha experiência com a Renantur foi muito boa, mas o quarto que fiquei no hotel não foi bom, pequeno e tinha uma beliche em cima da cama de casal que o meu esposo bateu a testa e cortou, o restaurante também não me agradou, tinha até sobremesa azeda. Mas isso não depende do Renan, que é muito competente.','','{}',13),
('S. Marina','Avaliação no Google',4,'Eu e meu esposo já viajamos outras vezes com o Renan, nada a reclamar, sempre atencioso e gentil. Voltarei mais vezes. Obrigada pelo passeio.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNcsRmn4GCbK3RvIpU_VbEqDDL6bTAJ1BJiZoqSFACA2X9ArgmZ9qOtDJ2BLl_pHwOv32C7fYijTX2miovgMGf81XS27gS5rl9N-SAz1oijHD8FQ0RZImqhVnNNCk3veESiS1MF7sYRLX8=w600-h450-p-k-no'],14),
('Josiane Silva','Avaliação no Google',5,'Amei a viagem, com certeza farei outras.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmOk-h0MskTWWhJNZxU6CR4g5tsQiaA9fvbKmGInYs0ibrqy-JNGSoryIGUYO0fXA3zKkisUigAALDRIS1-RZi4NAm6OMJgzH2HJ98P6cpNBeIbzumOov66cephC3YNT1UA21XPiQJIDOZVG=w600-h450-p-k-no'],15),
('Camilli Vytória','Avaliação no Google',5,'Um ótimo serviço, simpática e animação, tudo muito organizado, já quero a próxima, amei!','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmOLDx7Yy_3X5x86AHbFHpeHb7CJ9IPLZy0qCPgY-l2xpltg2nJqZ1jbgsTO1tIIMkwh7tt_v03EoUjywI989NaCNIK3Ih7V19Sms4kdhs7tThl3GxDcphm3J-tb4ZT3Ut3TlmzniQ_uqqI=w600-h450-p-k-no'],16),
('Carla Martins','Avaliação no Google',5,'Experiência muito boa! Renan é atencioso e sempre tentando proporcionar a melhor experiência... Recomendo 🙂','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNbUS7IvKeefGvFfRs5cjNnBnt1UTMOnHxkaEqypfxHIQhYw_39N0Vs4a6ReU2Lyyd3ulQydiln7ohFN1MesqxNRC4qli89rWGDpiWltZZwfbzOPa981QfBkz37_1VWg7B9zAnRWpQ71oZa=w300-h450-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmN0jWxHZnt7fMkHUEX9x8s6o-f2sOgl-AH8Fq5D3OVNWDPDFfV4XjSjuME0IQdtvjxf_NLhw-EBdIbTfHag2s-hbfHUdA7_KCL9gmGL4kdW-Xe52E8elc7y3BBN7QQm5nsfkt_wbz45nUk=w300-h225-p-k-no'],17),
('Dora Silva','Avaliação no Google',5,'Viagem maravilhosa! A empresa Renantur é de excelência e tem todo o compromisso e cuidado com todos. Super indico e espero viajar mais vezes com essa empresa.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmOQeLRDIv3Jp31nSBeSMpX9GMf40_VnZspeyN27JOx_2rOa2dzdottU4myBNf8l88tuZUBVDv91QQjRlgNlwBJYTYBMXurp-IpaxfKF9u-mutAI-skeMjsB16B2eeLMq4yg1qxDELeLShxW=w600-h450-p-k-no'],18),
('Franciene Calisto','Avaliação no Google',5,'Viagem incrível, a experiência das cataratas foi inesquecível. Renan super atencioso, fez tudo para que nossa viagem fosse a melhor. Super indico.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmNFlfanqcs8IFNSXZzAQxZLamuK3FHF0IKKH-z8n-5NCpyOtnNGqWQ1CgDhxQ_9zH5GZHeUNg-Y38UlsQ_VbodSPZztjCMCVnkZNNcN-5PV3OO0qQCK9qFiKLhZnkHehoIg9mnZyqH2OKGR=w300-h225-p-k-no','https://lh3.googleusercontent.com/grass-cs/ACvplmOymgY-E7c24v_xNiJPShr5MI5MTB4S06JWG3OO4gOUN2KVZxg2qfa--HdIovWkyNLVxJvg_ck5sgo9gzRnJOfOApZpn9pasUDlYhEYVO_8PAVmfGMigeDj_a5cJ-lIIsss_WrElK7euw-q=w300-h225-p-k-no'],19),
('Cláudia Elaine Almeida Rezende','Avaliação no Google',5,'Empresa excelente! Atenção ímpar! Cumpriu todo o cronograma de viagem. Todos os serviços de excelência. Sem contar que o Renan é uma pessoa maravilhosa, educada e prestativa. Super indico e espero viajar mais vezes pela empresa.','',array['https://lh3.googleusercontent.com/grass-cs/ACvplmOH9iIIk9KfkHS3ySWF4UVZ0D0jSDlZrYQG40SOKSBlwUgG36mu4wVKY3LcsECg6BMoy4rJRFCNGl-TXErvO9evcNjt4wqra6gJPDxNgYYe6NyIqtzGDacKICSFBq3jWj-QwCSmO7usPDA=w600-h450-p-k-no'],20);
